### ISSUE TITLE
error_class="TypeError" error="can't convert StringIO into String" when sending record to Kinesis

### ISSUE THREAD

**Issue by danielgollas** [awslabs/aws-fluent-plugin-kinesis#12]
Hi,

I am running into an issue where there is a error_class="TypeError" error="can't convert StringIO into String" with the following trace:
```
2014-12-23 01:53:20 +0000 [warn]: plugin/out_kinesis.rb:119:block in write: {:stream_name=>"tm_logger", :data=>"{\"json\":\"nevin is a dict\",\"time\":\"2014-12-23T01:53:17Z\",\"tag\":\"kinesis.test\"}", :partition_key=>"7fcba520-4120-435a-af24-8e2b40dda171"}
2014-12-23 01:53:20 +0000 [warn]: fluent/output.rb:369:rescue in try_flush: failed to flush the buffer. error_class="TypeError" error="can't convert StringIO into String" plugin_id="object:13be4c0"
2014-12-23 01:53:20 +0000 [warn]: fluent/output.rb:370:rescue in try_flush: retry count exceededs limit.
  2014-12-23 01:53:20 +0000 [warn]: /home/fluent/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/base64.rb:65:in `pack'
  2014-12-23 01:53:20 +0000 [warn]: /home/fluent/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/base64.rb:65:in `strict_encode64'
  2014-12-23 01:53:20 +0000 [warn]: /home/fluent/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/aws-sdk-core-2.0.16/lib/aws-sdk-core/json/builder.rb:57:in `format'
  2014-12-23 01:53:20 +0000 [warn]: /home/fluent/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/aws-sdk-core-2.0.16/lib/aws-sdk-core/json/builder.rb:24:in `block in structure'
  2014-12-23 01:53:20 +0000 [warn]: /home/fluent/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/aws-sdk-core-2.0.16/lib/aws-sdk-core/json/builder.rb:20:in `each'
  2014-12-23 01:53:20 +0000 [warn]: /home/fluent/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/aws-sdk-core-2.0.16/lib/aws-sdk-core/json/builder.rb:20:in `with_object'
  2014-12-23 01:53:20 +0000 [warn]: /home/fluent/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/aws-sdk-core-2.0.16/lib/aws-sdk-core/json/builder.rb:20:in `structure'
  2014-12-23 01:53:20 +0000 [warn]: /home/fluent/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/aws-sdk-core-2.0.16/lib/aws-sdk-core/json/builder.rb:53:in `format'
  2014-12-23 01:53:20 +0000 [warn]: /home/fluent/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/aws-sdk-core-2.0.16/lib/aws-sdk-core/json/builder.rb:11:in `to_json'
  2014-12-23 01:53:20 +0000 [warn]: /home/fluent/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/aws-sdk-core-2.0.16/lib/aws-sdk-core/json/rpc_body_handler.rb:20:in `build_json'
  2014-12-23 01:53:20 +0000 [warn]: /home/fluent/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/aws-sdk-core-2.0.16/lib/aws-sdk-core/json/rpc_body_handler.rb:8:in `call'
  2014-12-23 01:53:20 +0000 [warn]: /home/fluent/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/aws-sdk-core-2.0.16/lib/aws-sdk-core/json/rpc_headers_handler.rb:10:in `call'
  2014-12-23 01:53:20 +0000 [warn]: /home/fluent/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/aws-sdk-core-2.0.16/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'
  2014-12-23 01:53:20 +0000 [warn]: /home/fluent/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/aws-sdk-core-2.0.16/lib/seahorse/client/plugins/restful_bindings.rb:13:in `call'
  2014-12-23 01:53:20 +0000 [warn]: /home/fluent/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/aws-sdk-core-2.0.16/lib/seahorse/client/plugins/endpoint.rb:35:in `call'
  2014-12-23 01:53:20 +0000 [warn]: /home/fluent/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/aws-sdk-core-2.0.16/lib/seahorse/client/logging/handler.rb:10:in `call'
  2014-12-23 01:53:20 +0000 [warn]: /home/fluent/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/aws-sdk-core-2.0.16/lib/seahorse/client/plugins/param_validation.rb:22:in `call'
  2014-12-23 01:53:20 +0000 [warn]: /home/fluent/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/aws-sdk-core-2.0.16/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
  2014-12-23 01:53:20 +0000 [warn]: /home/fluent/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/aws-sdk-core-2.0.16/lib/seahorse/client/plugins/param_conversion.rb:22:in `call'
  2014-12-23 01:53:20 +0000 [warn]: /home/fluent/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/aws-sdk-core-2.0.16/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
  2014-12-23 01:53:20 +0000 [warn]: /home/fluent/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/aws-sdk-core-2.0.16/lib/seahorse/client/request.rb:70:in `send_request'
  2014-12-23 01:53:20 +0000 [warn]: /home/fluent/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/aws-sdk-core-2.0.16/lib/seahorse/client/base.rb:215:in `block (2 levels) in define_operation_methods'
  2014-12-23 01:53:20 +0000 [warn]: /home/fluent/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/fluent-plugin-kinesis-0.2.0/lib/fluent/plugin/out_kinesis.rb:120:in `block in write'
  2014-12-23 01:53:20 +0000 [warn]: /home/fluent/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/fluentd-0.10.58/lib/fluent/plugin/buf_memory.rb:62:in `feed_each'
  2014-12-23 01:53:20 +0000 [warn]: /home/fluent/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/fluentd-0.10.58/lib/fluent/plugin/buf_memory.rb:62:in `msgpack_each'
  2014-12-23 01:53:20 +0000 [warn]: /home/fluent/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/fluent-plugin-kinesis-0.2.0/lib/fluent/plugin/out_kinesis.rb:98:in `write'
  2014-12-23 01:53:20 +0000 [warn]: /home/fluent/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/fluentd-0.10.58/lib/fluent/buffer.rb:300:in `write_chunk'
  2014-12-23 01:53:20 +0000 [warn]: /home/fluent/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/fluentd-0.10.58/lib/fluent/buffer.rb:280:in `pop'
  2014-12-23 01:53:20 +0000 [warn]: /home/fluent/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/fluentd-0.10.58/lib/fluent/output.rb:315:in `try_flush'
  2014-12-23 01:53:20 +0000 [warn]: /home/fluent/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/fluentd-0.10.58/lib/fluent/output.rb:136:in `run'
```

I added an extra log message at the top printing the data_to_put variable in the write(chunk) function of out_kinesis.rb

The problem was also described by someone else here: http://stackoverflow.com/questions/27578440/td-agent-is-not-not-forwarding-messages-to-kinesis-using-kinesis-plugin#_=_

Thanks!
Daniel Gollas

**Comment by danielgollas** [comment]
Hi! Any updates on this issue? Is anybody else running this version successfully?

**Comment by imaifactory** [comment]
Hi @danielgollas , sorry for my late response.
Can you update aws-sdk-core? Recently the line we are seeing issue in SDK has been updated.
It might help.
https://github.com/aws/aws-sdk-core-ruby/pull/180

However I could not re-produce your issue with my environment. I am putting records to Amazon Kinesis successfully with td-agent. My config is here.
```
<match kinesis.test>
  type kinesis
  stream_name fluentd2
  region ap-northeast-1
  flush_interval 100
  random_partition_key
  detach_process 2
  num_threads 100
</match>
```

Can you share your config for td-agent as well? I will dig it. Velocity(records per seconds) is also good help for me to dig deeper.

Thanks!

**Comment by imaifactory** [comment]
Closing the issue. If anyone is still working with this, please open a new issue.
I believe we can achieve higher throughput easily because we now support PutRecords API.
https://github.com/awslabs/aws-fluent-plugin-kinesis/releases/tag/v0.3.0
