### ISSUE TITLE
http_proxy doesn't seem to work

### ISSUE THREAD

**Issue by phagunbaya** [awslabs/aws-fluent-plugin-kinesis#154]
I have set `http_proxy` to `https://username:password@host:port` as an environment variable. The plugin crashes complaining about the authentication.

```
2018-07-24 01:49:54 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
/usr/lib/ruby/2.4.0/net/http/response.rb:122:in `error!': 407 "Proxy Authentication Required" (Net::HTTPServerException)
        from /usr/lib/ruby/2.4.0/net/http/response.rb:131:in `value'
        from /usr/lib/ruby/2.4.0/net/http.rb:925:in `connect'
        from /usr/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
        from /usr/lib/ruby/2.4.0/net/http.rb:876:in `start'
        from /usr/lib/ruby/gems/2.4.0/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
        from /usr/lib/ruby/gems/2.4.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
        from /usr/lib/ruby/gems/2.4.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
        from /usr/lib/ruby/gems/2.4.0/gems/rest-client-2.0.2/lib/restclient/resource.rb:51:in `get'
        from /usr/lib/ruby/gems/2.4.0/gems/kubeclient-1.1.4/lib/kubeclient/common.rb:328:in `block in api'
        from /usr/lib/ruby/gems/2.4.0/gems/kubeclient-1.1.4/lib/kubeclient/common.rb:58:in `handle_exception'
        from /usr/lib/ruby/gems/2.4.0/gems/kubeclient-1.1.4/lib/kubeclient/common.rb:327:in `api'
        from /usr/lib/ruby/gems/2.4.0/gems/kubeclient-1.1.4/lib/kubeclient/common.rb:322:in `api_valid?'
        from /usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-kubernetes_metadata_filter-2.1.2/lib/fluent/plugin/filter_kubernetes_metadata.rb:234:in `configure'
        from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.0/lib/fluent/plugin.rb:164:in `configure'
        from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.0/lib/fluent/agent.rb:152:in `add_filter'
        from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.0/lib/fluent/agent.rb:70:in `block in configure'
        from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.0/lib/fluent/agent.rb:64:in `each'
        from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.0/lib/fluent/agent.rb:64:in `configure'
        from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.0/lib/fluent/root_agent.rb:112:in `configure'
        from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.0/lib/fluent/engine.rb:131:in `configure'
        from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.0/lib/fluent/engine.rb:96:in `run_configure'
        from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.0/lib/fluent/supervisor.rb:795:in `run_configure'
        from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.0/lib/fluent/supervisor.rb:579:in `dry_run'
        from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.0/lib/fluent/supervisor.rb:597:in `supervise'
        from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.0/lib/fluent/supervisor.rb:502:in `run_supervisor'
        from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.0/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
        from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.0/bin/fluentd:8:in `<top (required)>'
        from /usr/bin/fluentd:23:in `load'
        from /usr/bin/fluentd:23:in `<main>'
```

**Comment by phagunbaya** [comment]
Any update? It's a blocker for us.

**Comment by simukappu** [comment]
Thank you for your reporting.
According to your stack trace, this issue seems to be related another gem such as `fluent-plugin-kubernetes_metadata_filter-2.1.2` or `fluentd-1.2.0` itself. Is this an unique issue when you use `fluent-plugin-kinesis` plugin?

**Comment by simukappu** [comment]
Closing this issue for now. Please reopen if required.
