### ISSUE TITLE
Gem dependency issue latest aws kinesis/core gems.

### ISSUE THREAD

**Issue by akash0710** [awslabs/aws-fluent-plugin-kinesis#202]
We are using plugin version 3.2.1 but issue will occur in the latest version also.
new gems were released on June 10, 2020  from aws for aws kinesis and aws core

https://rubygems.org/gems/aws-sdk-kinesis/versions/1.0.0.rc1
https://rubygems.org/gems/aws-sdk-core/versions/3.0.0.rc1

https://github.com/awslabs/aws-fluent-plugin-kinesis/blob/v3.2.1/fluent-plugin-kinesis.gemspec

Below is the error stack

> 2020-06-11 03:29:57 -0700 [warn]: #0 thread exited by unexpected error plugin=Fluent::Plugin::KinesisStreamsAggregatedOutput title=:flush_thread_5 error_class=LoadError error="cannot load such file -- aws-sdk-core/plugins/http_checksum.rb"
2020-06-11 03:29:57 -0700 [error]: #0 unexpected error error_class=LoadError error="cannot load such file -- aws-sdk-core/plugins/http_checksum.rb"
  2020-06-11 03:29:57 -0700 [error]: #0 /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2020-06-11 03:29:57 -0700 [error]: #0 /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2020-06-11 03:29:57 -0700 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-kinesis-1.24.0/lib/aws-sdk-kinesis/client.rb:27:in `<top (required)>'
  2020-06-11 03:29:57 -0700 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-kinesis-1.24.0/lib/aws-sdk-kinesis.rb:13:in `require_relative'
  2020-06-11 03:29:57 -0700 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-kinesis-1.24.0/lib/aws-sdk-kinesis.rb:13:in `<top (required)>'
  2020-06-11 03:29:57 -0700 [error]: #0 /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2020-06-11 03:29:57 -0700 [error]: #0 /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2020-06-11 03:29:57 -0700 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kinesis-3.2.1/lib/fluent/plugin/kinesis_helper/client.rb:93:in `client_class'
  2020-06-11 03:29:57 -0700 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kinesis-3.2.1/lib/fluent/plugin/kinesis_helper/client.rb:85:in `client'
  2020-06-11 03:29:57 -0700 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kinesis-3.2.1/lib/fluent/plugin/out_kinesis_streams_aggregated.rb:50:in `block in write'
  2020-06-11 03:29:57 -0700 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kinesis-3.2.1/lib/fluent/plugin/kinesis_helper/api.rb:91:in `batch_request_with_retry'
  2020-06-11 03:29:57 -0700 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kinesis-3.2.1/lib/fluent/plugin/kinesis.rb:151:in `block (2 levels) in write_records_batch'
  2020-06-11 03:29:57 -0700 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kinesis-3.2.1/lib/fluent/plugin/kinesis_helper/api.rb:86:in `split_to_batches'
  2020-06-11 03:29:57 -0700 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kinesis-3.2.1/lib/fluent/plugin/kinesis.rb:149:in `block in write_records_batch'
  2020-06-11 03:29:57 -0700 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.0/lib/fluent/plugin/buffer/memory_chunk.rb:81:in `open'
  2020-06-11 03:29:57 -0700 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.0/lib/fluent/plugin/buffer/memory_chunk.rb:81:in `open'
  2020-06-11 03:29:57 -0700 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kinesis-3.2.1/lib/fluent/plugin/kinesis.rb:147:in `write_records_batch'
  2020-06-11 03:29:57 -0700 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kinesis-3.2.1/lib/fluent/plugin/out_kinesis_streams_aggregated.rb:47:in `write'
  2020-06-11 03:29:57 -0700 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.0/lib/fluent/plugin/output.rb:1133:in `try_flush'
  2020-06-11 03:29:57 -0700 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.0/lib/fluent/plugin/output.rb:1439:in `flush_thread_run'
  2020-06-11 03:29:57 -0700 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.0/lib/fluent/plugin/output.rb:461:in `block (2 levels) in start'
  2020-06-11 03:29:57 -0700 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.10.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2020-06-11 03:29:57 -0700 [error]: #0 cannot load such file -- aws-sdk-core/plugins/http_checksum.rb path="aws-sdk-core/plugins/http_checksum.rb" error_class=LoadError error="cannot load such file -- aws-sdk-core/plugins/http_checksum.rb"

**Comment by simukappu** [comment]
Hi,
Thank you for your reporting. We've just released the latest v3.2.3 plugin here.
https://rubygems.org/gems/fluent-plugin-kinesis/versions/3.2.3

We've tested this gem with the latest td-agent 3.8.0 and the latest Fluentd 1.11.1 dependency like this.
https://travis-ci.org/github/awslabs/aws-fluent-plugin-kinesis
https://github.com/awslabs/aws-fluent-plugin-kinesis/blob/master/.travis.yml

Which Fluentd or td-agent version are you using? How do you install them?

**Comment by akash0710** [comment]
This issue got resolved as aws updated the gems which solved the dependency between aws-sdk-kinesis and aws-sdk-core.

**Comment by simukappu** [comment]
Thank you! Closing this issue.
