### ISSUE TITLE
cannot load such file -- aws-sdk-core path="aws-sdk-core" error_class=LoadError error="cannot load such file -- aws-sdk-core

### ISSUE THREAD

**Issue by da-head0** [awslabs/aws-fluent-plugin-kinesis#220]
Hello,

when I install fluentd with git clone and bundle, and install `fluent-plugin-kinesis` with same method (using git clone & bundle),
this error shows up.

2022-05-12 11:20:07 +0000 [info]: parsing config file is succeeded path="./fluent/fluentd_blackhole.conf"
2022-05-12 11:20:07 +0000 [info]: starting fluentd-1.14.6 without supervision pid=1875 ruby="2.7.2"
2022-05-12 11:20:07 +0000 [info]: adding match pattern="appexception.**" type="kinesis_streams"
2022-05-12 11:20:07 +0000 [error]: cannot load such file -- aws-sdk-core path="aws-sdk-core" error_class=LoadError error="cannot load such file -- aws-sdk-core"
  2022-05-12 11:20:07 +0000 [error]: /home/test/apps/fluentd/aws-fluent-plugin-kinesis/lib/fluent/plugin/kinesis_helper/client.rb:16:in `require'
  2022-05-12 11:20:07 +0000 [error]: /home/test/apps/fluentd/aws-fluent-plugin-kinesis/lib/fluent/plugin/kinesis_helper/client.rb:16:in `<top (required)>'
  2022-05-12 11:20:07 +0000 [error]: /home/test/apps/fluentd/aws-fluent-plugin-kinesis/lib/fluent/plugin/kinesis.rb:18:in `require'
  2022-05-12 11:20:07 +0000 [error]: /home/test/apps/fluentd/aws-fluent-plugin-kinesis/lib/fluent/plugin/kinesis.rb:18:in `<top (required)>'
  2022-05-12 11:20:07 +0000 [error]: /home/test/apps/fluentd/aws-fluent-plugin-kinesis/lib/fluent/plugin/out_kinesis_streams.rb:15:in `require'
  2022-05-12 11:20:07 +0000 [error]: /home/test/apps/fluentd/aws-fluent-plugin-kinesis/lib/fluent/plugin/out_kinesis_streams.rb:15:in `<top (required)>'
  2022-05-12 11:20:07 +0000 [error]: /home/test/apps/fluentd/lib/fluent/registry.rb:87:in `require'
  2022-05-12 11:20:07 +0000 [error]: /home/test/apps/fluentd/lib/fluent/registry.rb:87:in `search'
  2022-05-12 11:20:07 +0000 [error]: /home/test/apps/fluentd/lib/fluent/registry.rb:44:in `lookup'
  2022-05-12 11:20:07 +0000 [error]: /home/test/apps/fluentd/lib/fluent/plugin.rb:169:in `new_impl'
  2022-05-12 11:20:07 +0000 [error]: /home/test/apps/fluentd/lib/fluent/plugin.rb:114:in `new_output'
  2022-05-12 11:20:07 +0000 [error]: /home/test/apps/fluentd/lib/fluent/agent.rb:130:in `add_match'
  2022-05-12 11:20:07 +0000 [error]: /home/test/apps/fluentd/lib/fluent/agent.rb:74:in `block in configure'
  2022-05-12 11:20:07 +0000 [error]: /home/test/apps/fluentd/lib/fluent/agent.rb:64:in `each'
  2022-05-12 11:20:07 +0000 [error]: /home/test/apps/fluentd/lib/fluent/agent.rb:64:in `configure'
  2022-05-12 11:20:07 +0000 [error]: /home/test/apps/fluentd/lib/fluent/root_agent.rb:149:in `configure'
  2022-05-12 11:20:07 +0000 [error]: /home/test/apps/fluentd/lib/fluent/engine.rb:105:in `configure'
  2022-05-12 11:20:07 +0000 [error]: /home/test/apps/fluentd/lib/fluent/engine.rb:80:in `run_configure'
  2022-05-12 11:20:07 +0000 [error]: /home/test/apps/fluentd/lib/fluent/supervisor.rb:719:in `block in run_worker'
  2022-05-12 11:20:07 +0000 [error]: /home/test/apps/fluentd/lib/fluent/supervisor.rb:971:in `main_process'
  2022-05-12 11:20:07 +0000 [error]: /home/test/apps/fluentd/lib/fluent/supervisor.rb:711:in `run_worker'
  2022-05-12 11:20:07 +0000 [error]: /home/test/apps/fluentd/lib/fluent/command/fluentd.rb:376:in `<top (required)>'
  2022-05-12 11:20:07 +0000 [error]: /home/test/apps/fluentd/bin/fluentd:15:in `require'
  2022-05-12 11:20:07 +0000 [error]: /home/test/apps/fluentd/bin/fluentd:15:in `<top (required)>'
  2022-05-12 11:20:07 +0000 [error]: /usr/local/rvm/gems/ruby-2.7.2/bin/fluentd:23:in `load'
  2022-05-12 11:20:07 +0000 [error]: /usr/local/rvm/gems/ruby-2.7.2/bin/fluentd:23:in `<main>'
  2022-05-12 11:20:07 +0000 [error]: /usr/local/rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:24:in `eval'
  2022-05-12 11:20:07 +0000 [error]: /usr/local/rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:24:in `<main>'

I tried with `Centos 7` and `Amazonlinux2`. The error is same.

when I install fluentd with git clone and bundle, and install `fluent-plugin-kinesis` plugin with gem, 
this error comes up.

2022-05-12 11:14:41 +0000 [info]: parsing config file is succeeded path="./fluent/fluentd_blackhole.conf"
2022-05-12 11:14:41 +0000 [info]: starting fluentd-1.14.6 without supervision pid=32102 ruby="2.7.2"
2022-05-12 11:14:41 +0000 [info]: adding match pattern="appexception.**" type="kinesis_streams"
2022-05-12 11:14:41 +0000 [error]: config error file="./fluent/fluentd_blackhole.conf" error_class=Fluent::NotFoundPluginError error="Unknown output plugin 'kinesis_streams'. Run 'gem search -rd fluent-plugin' to find plugins"

but when I install fluentd & this plugin with gem, everything works fine,
but I want to install fluentd with specific folder, and want to use this plugin.

Please help.

**Comment by da-head0** [comment]
I found out. when I cd to other path than `/path-to-that-I-git-clone-fluentd` and command `/usr/local/rvm/gems/ruby-2.7.2/bin/fluentd -c /path-to/fluentd.conf`, it works like a charm.

**Comment by simukappu** [comment]
Closing this issue for now. Please reopen if required.
