### ISSUE TITLE
Unclear error messages being logged: could it be more detailed?

### ISSUE THREAD

**Issue by francesco-russo** [awslabs/aws-fluent-plugin-kinesis#28]
Hi there,
we recently have observed a relatively high number of stack-traces as the following one on our fluent-kinesis agents:

```
2015-07-31 13:00:08 +0100 [warn]: temporarily failed to flush the buffer. next_retry=2015-07-31 13:00:03 +0100 error_class="Aws::Kinesis::Errors::InternalFailure" error="" plugin_id="object:156192f6c0d0"
2015-07-31 13:00:08 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call' 
2015-07-31 13:00:08 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/seahorse/client/plugins/param_conversion.rb:22:in `call' 
2015-07-31 13:00:08 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call' 
2015-07-31 13:00:08 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/seahorse/client/plugins/response_target.rb:18:in `call' 
2015-07-31 13:00:08 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/seahorse/client/request.rb:70:in `send_request' 
2015-07-31 13:00:08 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/seahorse/client/base.rb:216:in `block (2 levels) in define_operation_methods' 
2015-07-31 13:00:08 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-0.3.1.2/lib/fluent/plugin/out_kinesis.rb:232:in `put_records_with_retry' 
2015-07-31 13:00:08 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-0.3.1.2/lib/fluent/plugin/out_kinesis.rb:249:in `put_records_with_retry' 
2015-07-31 13:00:08 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-0.3.1.2/lib/fluent/plugin/out_kinesis.rb:128:in `block in write' 
2015-07-31 13:00:08 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-0.3.1.2/lib/fluent/plugin/out_kinesis.rb:127:in `each' 
2015-07-31 13:00:08 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-0.3.1.2/lib/fluent/plugin/out_kinesis.rb:127:in `write' 
2015-07-31 13:00:08 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/buffer.rb:325:in `write_chunk' 
2015-07-31 13:00:08 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/buffer.rb:304:in `pop' 
2015-07-31 13:00:08 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/output.rb:321:in `try_flush' 
2015-07-31 13:00:08 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/output.rb:140:in `run'
```
We have see this happening around the same time other errors, most likely related to a DNS issue, occurred. Here is that other stack-trace:

```
2015-08-12 17:58:05 +0100 [warn]: temporarily failed to flush the buffer. next_retry=2015-08-12 17:58:03 +0100 error_class="Seahorse::Client::NetworkingError" error="getaddrinfo: Temporary failure in name resolution" plugin_id="object:1581b1d6e0dc" 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http.rb:879:in `initialize'
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http.rb:879:in `open'
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http.rb:879:in `block in connect' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/timeout.rb:101:in `call'
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/timeout.rb:101:in `timeout'
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http.rb:878:in `connect'
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http.rb:858:in `start'
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/seahorse/client/net_http/connection_pool.rb:292:in `start_session' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/seahorse/client/net_http/connection_pool.rb:104:in `session_for' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/seahorse/client/net_http/handler.rb:108:in `session' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/seahorse/client/net_http/handler.rb:60:in `transmit' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/seahorse/client/net_http/handler.rb:34:in `call' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/seahorse/client/plugins/content_length.rb:12:in `call' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/aws-sdk-core/json/error_handler.rb:8:in `call' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/aws-sdk-core/plugins/request_signer.rb:78:in `call' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/aws-sdk-core/plugins/retry_errors.rb:88:in `call' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/aws-sdk-core/plugins/retry_errors.rb:119:in `retry_request' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/aws-sdk-core/plugins/retry_errors.rb:102:in `retry_if_possible' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/aws-sdk-core/plugins/retry_errors.rb:90:in `call' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/aws-sdk-core/plugins/retry_errors.rb:119:in `retry_request' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/aws-sdk-core/plugins/retry_errors.rb:102:in `retry_if_possible' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/aws-sdk-core/plugins/retry_errors.rb:90:in `call' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/aws-sdk-core/plugins/retry_errors.rb:119:in `retry_request' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/aws-sdk-core/plugins/retry_errors.rb:102:in `retry_if_possible' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/aws-sdk-core/plugins/retry_errors.rb:90:in `call' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/aws-sdk-core/json/rpc_body_handler.rb:9:in `call' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/aws-sdk-core/json/rpc_headers_handler.rb:10:in `call' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/seahorse/client/plugins/restful_bindings.rb:13:in `call' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/seahorse/client/plugins/endpoint.rb:31:in `call' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/seahorse/client/plugins/param_validation.rb:22:in `call' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/seahorse/client/plugins/param_conversion.rb:22:in `call' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/seahorse/client/plugins/response_target.rb:18:in `call' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/seahorse/client/request.rb:70:in `send_request' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.45/lib/seahorse/client/base.rb:216:in `block (2 levels) in define_operation_methods' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-0.3.1.2/lib/fluent/plugin/out_kinesis.rb:232:in `put_records_with_retry' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-0.3.1.2/lib/fluent/plugin/out_kinesis.rb:128:in `block in write' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-0.3.1.2/lib/fluent/plugin/out_kinesis.rb:127:in `each' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-0.3.1.2/lib/fluent/plugin/out_kinesis.rb:127:in `write' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/buffer.rb:325:in `write_chunk' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/buffer.rb:304:in `pop' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/output.rb:321:in `try_flush' 
2015-08-12 17:58:05 +0100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/output.rb:140:in `run'
```
It would be nice from an end-user perspective to have a better sense of why the agent gave up.

Thanks in advance!

**Comment by imaifactory** [comment]
@francesco-russo 

Hello, thanks for bringing up this.

The error `Aws::Kinesis::Errors::InternalFailure` looks [500 error from Amazon Kinesis](http://docs.aws.amazon.com/kinesis/latest/APIReference/CommonErrors.html). Is this recursively happening? If so, please kindly [open a support case](https://console.aws.amazon.com/support/) or post it to our [forum](https://forums.aws.amazon.com/forum.jspa?forumID=169).

`Seahorse::Client::NetworkingError` tells that your running machine's networking is something wrong at that time. I would recommend you to check network connection or configuration.

**Comment by francesco-russo** [comment]
Hi @imaifactory 
thanks for the prompt reply.

It is not happening constantly (the InternalFailure), but thanks for clarifying the nature of that error.
I'll check and see what happened at that time with the Kinesis team.

As far as the second error is concerned, that was my conclusion too, thanks for confirming.

**Comment by imaifactory** [comment]
@francesco-russo 

Thanks for confirmation.
Let me close this issue. Please open or re-open issue if any.
