### ISSUE TITLE
Can't push it from CentOS

### ISSUE THREAD

**Issue by dgomesbr** [awslabs/aws-fluent-plugin-kinesis#44]
We installed the *td-agent* and configure it as:

```
<source>
type tail
path /var/log/nginx/access.json.log
format json
tag nginx.access
</source>

## File output
## match tag=local.** and write to file
<match **>
type kinesis
stream_name teste-es
aws_key_id MYID
aws_sec_key MYSECKEY
region us-east-1
partition_key nginx
</match>
```

After a few requests to the nginx we keep seeing these errors and no message is produced to the Kinesis stream.
```log
2015-11-18 16:29:04 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2015-11-18 16:29:05 +0000 error_class="Aws::Kinesis::Errors::ValidationException" error="3 validation errors detected: Value '' at 'records.1.member.partitionKey' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'records.2.member.partitionKey' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'records.3.member.partitionKey' failed to satisfy constraint: Member must have length greater than or equal to 1" plugin_id="object:3f9730e90f14"
  2015-11-18 16:29:04 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.0/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
  2015-11-18 16:29:04 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.0/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
  2015-11-18 16:29:04 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.0/lib/seahorse/client/plugins/response_target.rb:21:in `call'
  2015-11-18 16:29:04 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.0/lib/seahorse/client/request.rb:70:in `send_request'
  2015-11-18 16:29:04 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.0/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
  2015-11-18 16:29:04 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-0.4.0/lib/fluent/plugin/out_kinesis.rb:271:in `put_records_with_retry'
  2015-11-18 16:29:04 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-0.4.0/lib/fluent/plugin/out_kinesis.rb:144:in `block in write'
  2015-11-18 16:29:04 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-0.4.0/lib/fluent/plugin/out_kinesis.rb:143:in `each'
  2015-11-18 16:29:04 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-0.4.0/lib/fluent/plugin/out_kinesis.rb:143:in `write'
  2015-11-18 16:29:04 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/buffer.rb:325:in `write_chunk'
  2015-11-18 16:29:04 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/buffer.rb:304:in `pop'
  2015-11-18 16:29:04 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/output.rb:321:in `try_flush'
  2015-11-18 16:29:04 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/output.rb:140:in `run'
2015-11-18 16:29:05 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2015-11-18 16:29:07 +0000 error_class="Aws::Kinesis::Errors::ValidationException" error="3 validation errors detected: Value '' at 'records.1.member.partitionKey' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'records.2.member.partitionKey' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'records.3.member.partitionKey' failed to satisfy constraint: Member must have length greater than or equal to 1" plugin_id="object:3f9730e90f14"
  2015-11-18 16:29:05 +0000 [warn]: suppressed same stacktrace
2015-11-18 16:29:07 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2015-11-18 16:29:11 +0000 error_class="Aws::Kinesis::Errors::ValidationException" error="3 validation errors detected: Value '' at 'records.1.member.partitionKey' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'records.2.member.partitionKey' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'records.3.member.partitionKey' failed to satisfy constraint: Member must have length greater than or equal to 1" plugin_id="object:3f9730e90f14"
  2015-11-18 16:29:07 +0000 [warn]: suppressed same stacktrace
2015-11-18 16:29:11 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2015-11-18 16:29:19 +0000 error_class="Aws::Kinesis::Errors::ValidationException" error="3 validation errors detected: Value '' at 'records.1.member.partitionKey' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'records.2.member.partitionKey' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'records.3.member.partitionKey' failed to satisfy constraint: Member must have length greater than or equal to 1" plugin_id="object:3f9730e90f14"
  2015-11-18 16:29:11 +0000 [warn]: suppressed same stacktrace
```

The log format being pushed from nginx is:
```config

    log_format le_json '{ "time": "$time_iso8601", '
       '"remote_addr": "$remote_addr", '
       '"remote_user": "$remote_user", '
       '"body_bytes_sent": "$body_bytes_sent", '
       '"request_time": "$request_time", '
       '"status": "$status", '
       '"request": "$request", '
       '"request_method": "$request_method", '
       '"http_referrer": "$http_referer", '
       '"http_user_agent": "$http_user_agent", '
       '"http_x_forwarded_for": "$http_x_forwarded_for" }';

    access_log /var/log/nginx/access.json.log le_json;
```

and the *ruby --version* gives me ```ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]```

**Comment by dgomesbr** [comment]
We just found the issue. The partition key should be a member of the json document. Is this documented anywhere?
