### ISSUE TITLE
[1.0RC] kinesis_producer plugin causes an error on td-agent

### ISSUE THREAD

**Issue by otaki-ryuta** [awslabs/aws-fluent-plugin-kinesis#49]
Kinesis_producer plugin causes an error on td-agent.
It looks like it is concerned with @kinesis_producer.credentials_refresh_delay.

- Ubuntu Server 14.04 Trusty
- td-agent 2.3.1

install instruction
```
$ curl -L https://toolbelt.treasuredata.com/sh/install-ubuntu-trusty-td-agent2.sh | sh
$ sudo td-agent-gem install fluent-plugin-kinesis --pre
```

full td-agent.log
```
2016-03-10 06:56:47 +0000 [info]: reading config file path="/etc/td-agent/td-agent.conf"
2016-03-10 06:56:47 +0000 [info]: starting fluentd-0.12.20
2016-03-10 06:56:47 +0000 [info]: gem 'fluent-mixin-config-placeholders' version '0.3.1'
2016-03-10 06:56:47 +0000 [info]: gem 'fluent-mixin-plaintextformatter' version '0.2.6'
2016-03-10 06:56:47 +0000 [info]: gem 'fluent-plugin-kinesis' version '1.0.0.rc3'
2016-03-10 06:56:47 +0000 [info]: gem 'fluent-plugin-mongo' version '0.7.12'
2016-03-10 06:56:47 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '1.5.4'
2016-03-10 06:56:47 +0000 [info]: gem 'fluent-plugin-s3' version '0.6.5'
2016-03-10 06:56:47 +0000 [info]: gem 'fluent-plugin-scribe' version '0.10.14'
2016-03-10 06:56:47 +0000 [info]: gem 'fluent-plugin-td' version '0.10.28'
2016-03-10 06:56:47 +0000 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.2'
2016-03-10 06:56:47 +0000 [info]: gem 'fluent-plugin-webhdfs' version '0.4.1'
2016-03-10 06:56:47 +0000 [info]: gem 'fluentd' version '0.12.20'
2016-03-10 06:56:47 +0000 [info]: adding match pattern="td.*.*" type="tdlog"
2016-03-10 06:56:47 +0000 [info]: adding match pattern="debug.**" type="stdout"
2016-03-10 06:56:47 +0000 [info]: adding match pattern="**" type="kinesis_producer"
2016-03-10 06:56:47 +0000 [info]: adding source type="forward"
2016-03-10 06:56:47 +0000 [info]: adding source type="http"
2016-03-10 06:56:47 +0000 [info]: adding source type="debug_agent"
2016-03-10 06:56:47 +0000 [info]: adding source type="tail"
2016-03-10 06:56:47 +0000 [info]: using configuration file: <ROOT>
  <match td.*.*>
    type tdlog
    apikey xxxxxx
    auto_create_table
    buffer_type file
    buffer_path /var/log/td-agent/buffer/td
    <secondary>
      type file
      path /var/log/td-agent/failed_records
      buffer_path /var/log/td-agent/failed_records.*
    </secondary>
  </match>
  <match debug.**>
    type stdout
  </match>
  <source>
    type forward
  </source>
  <source>
    type http
    port 8888
  </source>
  <source>
    type debug_agent
    bind 127.0.0.1
    port 24230
  </source>
  <source>
    @type tail
    path /var/log/apache2/access.log
    pos_file /var/log/td-agent/httpd-access.log.pos
    tag apache.access
    format apache2
  </source>
  <match **>
    @type kinesis_producer
    region us-west-2
    stream_name takipone-test
  </match>
</ROOT>
2016-03-10 06:56:47 +0000 [error]: unexpected error error_class=NoMethodError error=#<NoMethodError: undefined method `credentials_refresh_delay' for nil:NilClass>
  2016-03-10 06:56:47 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-1.0.0.rc3/lib/fluent/plugin/kinesis_helper/kpl.rb:44:in `client_options'
  2016-03-10 06:56:47 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-1.0.0.rc3/lib/fluent/plugin/kinesis_helper/client.rb:19:in `client'
  2016-03-10 06:56:47 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-1.0.0.rc3/lib/fluent/plugin/kinesis_helper/kpl.rb:29:in `block in start'
  2016-03-10 06:56:47 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/process.rb:485:in `call'
  2016-03-10 06:56:47 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/process.rb:485:in `detach_multi_process'
  2016-03-10 06:56:47 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-1.0.0.rc3/lib/fluent/plugin/kinesis_helper/kpl.rb:27:in `start'
  2016-03-10 06:56:47 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/agent.rb:67:in `block in start'
  2016-03-10 06:56:47 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/agent.rb:66:in `each'
  2016-03-10 06:56:47 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/agent.rb:66:in `start'
  2016-03-10 06:56:47 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/root_agent.rb:104:in `start'
  2016-03-10 06:56:47 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/engine.rb:225:in `start'
  2016-03-10 06:56:47 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/engine.rb:175:in `run'
  2016-03-10 06:56:47 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:597:in `run_engine'
  2016-03-10 06:56:47 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:148:in `block in start'
  2016-03-10 06:56:47 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:352:in `call'
  2016-03-10 06:56:47 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:352:in `main_process'
  2016-03-10 06:56:47 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:325:in `block in supervise'
  2016-03-10 06:56:47 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:324:in `fork'
  2016-03-10 06:56:47 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:324:in `supervise'
  2016-03-10 06:56:47 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:142:in `start'
  2016-03-10 06:56:47 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/command/fluentd.rb:171:in `<top (required)>'
  2016-03-10 06:56:47 +0000 [error]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2016-03-10 06:56:47 +0000 [error]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2016-03-10 06:56:47 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/bin/fluentd:6:in `<top (required)>'
  2016-03-10 06:56:47 +0000 [error]: /opt/td-agent/embedded/bin/fluentd:23:in `load'
  2016-03-10 06:56:47 +0000 [error]: /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
  2016-03-10 06:56:47 +0000 [error]: /usr/sbin/td-agent:7:in `load'
  2016-03-10 06:56:47 +0000 [error]: /usr/sbin/td-agent:7:in `<main>'
2016-03-10 06:56:47 +0000 [info]: shutting down fluentd
2016-03-10 06:56:47 +0000 [info]: shutting down output type="tdlog" plugin_id="object:3fca814a9558"
2016-03-10 06:56:47 +0000 [info]: shutting down output type="stdout" plugin_id="object:3fca83e3ee18"
2016-03-10 06:56:47 +0000 [info]: process finished code=0
2016-03-10 06:56:47 +0000 [warn]: process died within 1 second. exit.
```

**Comment by riywo** [comment]
Hi @otaki-ryuta ,

Thank you for reporting. I assumed that `config_section` is instantiated if the section is not specified, but it is never happened.

At this moment, I just changed the section required so that you have to specify an empty section even if you don't want to specify any params in the section.

````
<match your_tag>
  @type kinesis_producer
  region us-east-1
  stream_name your_stream
  partition_key key  # Otherwise, use random partition key
  <kinesis_producer> # You can't omit this section!
  </kinesis_producer>
</match>
````

**Comment by riywo** [comment]
Now, v1.0.0.rc5 does not require `kinesis_producer` section. You can use the config before.

**Comment by takipone** [comment]
Thanks! It works fine.
