### ISSUE TITLE
http_proxy error ..urgent help required

### ISSUE THREAD

**Issue by iamhasibrahman** [awslabs/aws-fluent-plugin-kinesis#57]
HTTP proxy settings giving this error ..please help ..

2016-03-22 13:23:32 +1100 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-22 13:23:48 +1100 error_class="Net::HTTPServerException" error="407 \"authenticationrequired\"" plugin_id="object:3f81117b0aa8"
  2016-03-22 13:23:32 +1100 [warn]: suppressed same stacktrace
2016-03-22 13:23:48 +1100 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-22 13:24:16 +1100 error_class="Net::HTTPServerException" error="407 \"authenticationrequired\"" plugin_id="object:3f81117b0aa8"
  2016-03-22 13:23:48 +1100 [warn]: suppressed same stacktrace
2016-03-22 13:24:17 +1100 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-22 13:25:24 +1100 error_class="Net::HTTPServerException" error="407 \"authenticationrequired\"" plugin_id="object:3f81117b0aa8"
  2016-03-22 13:24:17 +1100 [warn]: suppressed same stacktrace
2016-03-22 13:25:24 +1100 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-22 13:27:22 +1100 error_class="Net::HTTPServerException" error="407 \"authenticationrequired\"" plugin_id="object:3f81117b0aa8"
  2016-03-22 13:25:24 +1100 [warn]: suppressed same stacktrace
2016-03-22 13:27:22 +1100 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-22 13:31:07 +1100 error_class="Net::HTTPServerException" error="407 \"authenticationrequired\"" plugin_id="object:3f81117b0aa8"
  2016-03-22 13:27:22 +1100 [warn]: suppressed same stacktrace
2016-03-22 13:30:03 +1100 [info]: shutting down fluentd
2016-03-22 13:30:03 +1100 [info]: shutting down input type="forward" plugin_id="object:3f811335afd8"
2016-03-22 13:30:03 +1100 [info]: shutting down input type="http" plugin_id="object:3f8113355894"
2016-03-22 13:30:03 +1100 [info]: shutting down input type="debug_agent" plugin_id="object:3f81133489c8"
2016-03-22 13:30:03 +1100 [info]: shutting down input type="tail" plugin_id="object:3f8113361108"
2016-03-22 13:30:04 +1100 [info]: shutting down output type="stdout" plugin_id="object:3f811336bdc4"
2016-03-22 13:30:04 +1100 [info]: shutting down output type="kinesis_streams" plugin_id="object:3f81117b0aa8"
2016-03-22 13:30:04 +1100 [warn]: before_shutdown failed error="407 \"authenticationrequired\""
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http/response.rb:119:in `error!'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http/response.rb:128:in `value'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http.rb:915:in `connect'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http.rb:858:in `start'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/seahorse/client/net_http/connection_pool.rb:292:in `start_session'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/seahorse/client/net_http/connection_pool.rb:104:in `session_for'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/seahorse/client/net_http/handler.rb:109:in `session'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/seahorse/client/net_http/handler.rb:61:in `transmit'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/seahorse/client/net_http/handler.rb:35:in `call'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/seahorse/client/plugins/content_length.rb:12:in `call'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/aws-sdk-core/json/error_handler.rb:8:in `call'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/aws-sdk-core/plugins/request_signer.rb:84:in `call'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/aws-sdk-core/plugins/retry_errors.rb:87:in `call'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/aws-sdk-core/json/handler.rb:11:in `call'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/seahorse/client/plugins/endpoint.rb:41:in `call'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/aws-sdk-core/plugins/param_validator.rb:21:in `call'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/seahorse/client/plugins/response_target.rb:21:in `call'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/seahorse/client/request.rb:70:in `send_request'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-1.0.0/lib/fluent/plugin/out_kinesis_streams.rb:41:in `batch_request'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-1.0.0/lib/fluent/plugin/kinesis_helper/api.rb:79:in `batch_request_with_retry'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-1.0.0/lib/fluent/plugin/out_kinesis_streams.rb:26:in `block in write'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-1.0.0/lib/fluent/plugin/out_kinesis_streams.rb:25:in `each'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-1.0.0/lib/fluent/plugin/out_kinesis_streams.rb:25:in `write'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.22/lib/fluent/buffer.rb:351:in `write_chunk'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.22/lib/fluent/buffer.rb:330:in `pop'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.22/lib/fluent/plugin/buf_memory.rb:100:in `block in before_shutdown'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.22/lib/fluent/plugin/buf_memory.rb:96:in `before_shutdown'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.22/lib/fluent/output.rb:413:in `before_shutdown'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.22/lib/fluent/output.rb:169:in `block in run'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.22/lib/fluent/output.rb:168:in `synchronize'
  2016-03-22 13:30:04 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.22/lib/fluent/output.rb:168:in `run'
2016-03-22 13:30:04 +1100 [info]: process finished code=0
2016-03-22 13:30:05 +1100 [info]: reading config file path="/etc/td-agent/td-agent.conf"
2016-03-22 13:30:05 +1100 [info]: starting fluentd-0.12.22
2016-03-22 13:30:05 +1100 [info]: gem 'fluent-mixin-config-placeholders' version '0.3.1'
2016-03-22 13:30:05 +1100 [info]: gem 'fluent-mixin-plaintextformatter' version '0.2.6'
2016-03-22 13:30:05 +1100 [info]: gem 'fluent-plugin-kinesis' version '1.0.0'
2016-03-22 13:30:05 +1100 [info]: gem 'fluent-plugin-kinesis' version '0.4.0'
2016-03-22 13:30:05 +1100 [info]: gem 'fluent-plugin-mongo' version '0.7.12'
2016-03-22 13:30:05 +1100 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '1.5.4'
2016-03-22 13:30:05 +1100 [info]: gem 'fluent-plugin-s3' version '0.6.5'
2016-03-22 13:30:05 +1100 [info]: gem 'fluent-plugin-scribe' version '0.10.14'
2016-03-22 13:30:05 +1100 [info]: gem 'fluent-plugin-td' version '0.10.28'
2016-03-22 13:30:05 +1100 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.2'
2016-03-22 13:30:05 +1100 [info]: gem 'fluent-plugin-webhdfs' version '0.4.1'
2016-03-22 13:30:05 +1100 [info]: gem 'fluentd' version '0.12.22'
2016-03-22 13:30:05 +1100 [info]: gem 'fluentd' version '0.12.20'
2016-03-22 13:30:05 +1100 [info]: adding match pattern="**" type="kinesis_streams"
2016-03-22 13:30:05 +1100 [info]: adding match pattern="debug.**" type="stdout"
2016-03-22 13:30:05 +1100 [info]: adding source type="tail"
2016-03-22 13:30:05 +1100 [info]: adding source type="forward"
2016-03-22 13:30:05 +1100 [info]: adding source type="http"
2016-03-22 13:30:05 +1100 [info]: adding source type="debug_agent"
2016-03-22 13:30:05 +1100 [info]: using configuration file: <ROOT>
  <match **>
    @type kinesis_streams
    stream_name FluentDHeartbeat
    aws_key_id xxxxxx
    aws_sec_key xxxxxx
    http_proxy http://172.17.100.181:9090
    debug true
    region ap-southeast-2
    flush_interval 5s
    num_threads 1
  </match>
  <source>
    type tail
    path /var/log/td-agent/heartbeat.log
    tag heartbeat.access
    format none
    pos_file /var/log/td-agent/heartbeat.log.pos
  </source>
  <match debug.**>
    type stdout
  </match>
  <source>
    type forward
  </source>
  <source>
    type http
    port 8888
  </source>
  <source>
    type debug_agent
    bind 127.0.0.1
    port 24230
  </source>
</ROOT>
2016-03-22 13:30:05 +1100 [info]: following tail of /var/log/td-agent/heartbeat.log
2016-03-22 13:30:05 +1100 [info]: listening fluent socket on 0.0.0.0:24224
2016-03-22 13:30:05 +1100 [info]: listening dRuby uri="druby://127.0.0.1:24230" object="Engine"
D, [2016-03-22T13:30:46.512589 #15576] DEBUG -- : [Aws::Kinesis::Client 0 0.018289 0 retries] put_records(stream_name:"FluentDHeartbeat",records:[{data:"{\"message\":\"Tue Mar 22 13:30:43 AEDT 2016\"}",partition_key:"ad2ec04a08f7d96ed93cb74215f4349d"}]) Net::HTTPServerException 407 "authenticationrequired"

2016-03-22 13:30:46 +1100 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-22 13:30:47 +1100 error_class="Net::HTTPServerException" error="407 \"authenticationrequired\"" plugin_id="object:3fe9db3aabd8"
  2016-03-22 13:30:46 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http/response.rb:119:in `error!'
  2016-03-22 13:30:46 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http/response.rb:128:in `value'
  2016-03-22 13:30:46 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http.rb:915:in `connect'
  2016-03-22 13:30:46 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
  2016-03-22 13:30:46 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http.rb:858:in `start'
  2016-03-22 13:30:46 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/seahorse/client/net_http/connection_pool.rb:292:in `start_session'
  2016-03-22 13:30:46 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/seahorse/client/net_http/connection_pool.rb:104:in `session_for'
  2016-03-22 13:30:46 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/seahorse/client/net_http/handler.rb:109:in `session'
  2016-03-22 13:30:46 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/seahorse/client/net_http/handler.rb:61:in `transmit'
  2016-03-22 13:30:46 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/seahorse/client/net_http/handler.rb:35:in `call'
  2016-03-22 13:30:46 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/seahorse/client/plugins/content_length.rb:12:in `call'
  2016-03-22 13:30:46 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/aws-sdk-core/json/error_handler.rb:8:in `call'
  2016-03-22 13:30:46 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/aws-sdk-core/plugins/request_signer.rb:84:in `call'
  2016-03-22 13:30:46 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/aws-sdk-core/plugins/retry_errors.rb:87:in `call'
  2016-03-22 13:30:46 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/aws-sdk-core/json/handler.rb:11:in `call'
  2016-03-22 13:30:46 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'
  2016-03-22 13:30:46 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/seahorse/client/plugins/endpoint.rb:41:in `call'
  2016-03-22 13:30:46 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/aws-sdk-core/plugins/param_validator.rb:21:in `call'
  2016-03-22 13:30:46 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/aws-sdk-core/plugins/logging.rb:39:in `call'
  2016-03-22 13:30:46 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
  2016-03-22 13:30:46 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
  2016-03-22 13:30:46 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/seahorse/client/plugins/response_target.rb:21:in `call'
  2016-03-22 13:30:46 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/seahorse/client/request.rb:70:in `send_request'
  2016-03-22 13:30:46 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.14/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
  2016-03-22 13:30:46 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-1.0.0/lib/fluent/plugin/out_kinesis_streams.rb:41:in `batch_request'
  2016-03-22 13:30:46 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-1.0.0/lib/fluent/plugin/kinesis_helper/api.rb:79:in `batch_request_with_retry'
  2016-03-22 13:30:46 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-1.0.0/lib/fluent/plugin/out_kinesis_streams.rb:26:in `block in write'
  2016-03-22 13:30:46 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-1.0.0/lib/fluent/plugin/out_kinesis_streams.rb:25:in `each'
  2016-03-22 13:30:46 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-1.0.0/lib/fluent/plugin/out_kinesis_streams.rb:25:in `write'
  2016-03-22 13:30:46 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.22/lib/fluent/buffer.rb:351:in `write_chunk'
  2016-03-22 13:30:46 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.22/lib/fluent/buffer.rb:330:in `pop'
  2016-03-22 13:30:46 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.22/lib/fluent/output.rb:338:in `try_flush'
  2016-03-22 13:30:46 +1100 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.22/lib/fluent/output.rb:149:in `run'
D, [2016-03-22T13:30:47.418011 #15576] DEBUG -- : [Aws::Kinesis::Client 0 0.015474 0 retries] put_records(stream_name:"FluentDHeartbeat",records:[{data:"{\"message\":\"Tue Mar 22 13:30:43 AEDT 2016\"}",partition_key:"c23b30f2ae9e08c8b56b2cd1a9ed3132"}]) Net::HTTPServerException 407 "authenticationrequired"

2016-03-22 13:30:47 +1100 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-22 13:30:49 +1100 error_class="Net::HTTPServerException" error="407 \"authenticationrequired\"" plugin_id="object:3fe9db3aabd8"
  2016-03-22 13:30:47 +1100 [warn]: suppressed same stacktrace
D, [2016-03-22T13:30:49.487253 #15576] DEBUG -- : [Aws::Kinesis::Client 0 0.016633 0 retries] put_records(stream_name:"FluentDHeartbeat",records:[{data:"{\"message\":\"Tue Mar 22 13:30:43 AEDT 2016\"}",partition_key:"f20318016147ab2690b0fe79f151c273"}]) Net::HTTPServerException 407 "authenticationrequired"

2016-03-22 13:30:49 +1100 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-22 13:30:53 +1100 error_class="Net::HTTPServerException" error="407 \"authenticationrequired\"" plugin_id="object:3fe9db3aabd8"
  2016-03-22 13:30:49 +1100 [warn]: suppressed same stacktrace
D, [2016-03-22T13:30:53.465222 #15576] DEBUG -- : [Aws::Kinesis::Client 0 0.047881 0 retries] put_records(stream_name:"FluentDHeartbeat",records:[{data:"{\"message\":\"Tue Mar 22 13:30:43 AEDT 2016\"}",partition_key:"74722665315a868587d6228d2a9e97ad"}]) Net::HTTPServerException 407 "authenticationrequired"

2016-03-22 13:30:53 +1100 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-22 13:31:00 +1100 error_class="Net::HTTPServerException" error="407 \"authenticationrequired\"" plugin_id="object:3fe9db3aabd8"
  2016-03-22 13:30:53 +1100 [warn]: suppressed same stacktrace
D, [2016-03-22T13:31:00.990256 #15576] DEBUG -- : [Aws::Kinesis::Client 0 0.018406 0 retries] put_records(stream_name:"FluentDHeartbeat",records:[{data:"{\"message\":\"Tue Mar 22 13:30:43 AEDT 2016\"}",partition_key:"9e847c6a4655c8d448275cf8b296d3e2"}]) Net::HTTPServerException 407 "authenticationrequired"

2016-03-22 13:31:00 +1100 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-22 13:31:15 +1100 error_class="Net::HTTPServerException" error="407 \"authenticationrequired\"" plugin_id="object:3fe9db3aabd8"
  2016-03-22 13:31:00 +1100 [warn]: suppressed same stacktrace

**Comment by riywo** [comment]
Your proxy says `407 "authenticationrequired"`. Is it required to add username and password for `http_proxy` parameter? Because your config seems no authentication.

**Comment by iamhasibrahman** [comment]
Proxy requires authentication
And it's McAfee web gateway.

And we are passing the authorisation in this format

http://username:password@111.1111.111.111:8080

**Comment by riywo** [comment]
Your config is below from your log:
`http_proxy http://172.17.100.181:9090`

Could you try that URL for your `http_proxy` parameter?

**Comment by iamhasibrahman** [comment]
We could telnet etc.

**Comment by riywo** [comment]
Please try this:

    http_proxy http://username:password@111.1111.111.111:8080

It is difficult to support more since it depends on your proxy behavior. This plugin uses Ruby stdlib Net::HTTP, so could you try to search or ask Ruby community to work Net::HTTP with McAfee web gateway?

**Comment by iamhasibrahman** [comment]
Hey Riywo - You're right. This testing wasn't properly planned and I just realised that we should have Proxy admin standby to check the log. That way, we could have troubleshot it much better
