### ISSUE TITLE
aws-fluent-plugin-kinesis on aws-sdk-core-2.5.1

### ISSUE THREAD

**Issue by stevenc81** [awslabs/aws-fluent-plugin-kinesis#80]
Hello amazing AWS team,

Happy Monday! I hope you week starts off to a great start! We noticed there is a small issue with the new aws ruby SDK from last week suggesting the variable **region** couldn't be resolved after 2.5.1 (https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-core/lib/aws-sdk-core/credential_provider_chain.rb#L76). Wondering if this might be something we could resolve on the fluend plugin's end? 

`2016-08-05 09:08:26 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2016-08-05 09:08:27 +0000 error_class="NoMethodError" error="undefined method `region' for #<#<Class:0x007fb8401d0fb0>:0x007fb8401d0e70>" plugin_id="object:3fdc23fd232c"
  2016-08-05 09:08:26 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.5.1/lib/aws-sdk-core/credential_provider_chain.rb:76:in `assume_role_credentials'
  2016-08-05 09:08:26 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.5.1/lib/aws-sdk-core/credential_provider_chain.rb:12:in `block in resolve'
  2016-08-05 09:08:26 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.5.1/lib/aws-sdk-core/credential_provider_chain.rb:11:in `each'
  2016-08-05 09:08:26 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.5.1/lib/aws-sdk-core/credential_provider_chain.rb:11:in `resolve'
  2016-08-05 09:08:26 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-1.1.0/lib/fluent/plugin/kinesis_helper/credentials.rb:43:in `default_credentials_provider'
  2016-08-05 09:08:26 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-1.1.0/lib/fluent/plugin/kinesis_helper/credentials.rb:34:in `credentials'
  2016-08-05 09:08:26 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-1.1.0/lib/fluent/plugin/kinesis_helper/api.rb:42:in `client_options'
  2016-08-05 09:08:26 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-1.1.0/lib/fluent/plugin/kinesis_helper/client.rb:19:in `client'
  2016-08-05 09:08:26 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-1.1.0/lib/fluent/plugin/out_kinesis_firehose.rb:38:in `batch_request'
  2016-08-05 09:08:26 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-1.1.0/lib/fluent/plugin/kinesis_helper/api.rb:79:in `batch_request_with_retry'
  2016-08-05 09:08:26 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-1.1.0/lib/fluent/plugin/out_kinesis_firehose.rb:26:in `block in write'
  2016-08-05 09:08:26 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-1.1.0/lib/fluent/plugin/out_kinesis_firehose.rb:25:in `each'
  2016-08-05 09:08:26 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-1.1.0/lib/fluent/plugin/out_kinesis_firehose.rb:25:in `write'
  2016-08-05 09:08:26 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/buffer.rb:325:in `write_chunk'
  2016-08-05 09:08:26 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/buffer.rb:304:in `pop'
  2016-08-05 09:08:26 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/output.rb:321:in `try_flush'
  2016-08-05 09:08:26 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/output.rb:140:in `run'`

**Comment by riywo** [comment]
Thank you for reporting. I'll check this out.

**Comment by riywo** [comment]
Hi @stevenc81 ,

I've released the bug fixed version https://rubygems.org/gems/fluent-plugin-kinesis/versions/1.1.1 Please try this version and let me know if you have any problem.

Thanks
