### ISSUE TITLE
Fluent::BufferQueueLimitError and kinesis_produce freeze

### ISSUE THREAD

**Issue by llby** [awslabs/aws-fluent-plugin-kinesis#88]
I use fluentd v12.26 and aws-fluent-plugin-kinesis v1.1.0
When few days pass in production traffic.
fluentd has error `Fluent::BufferQueueLimitError`
and I can't kill kinesis_produce.
(and td-agent can't service restart.)

```
2016-10-17 11:08:57 +0900 [info]: reading config file path="/etc/td-agent/td-agent.conf"
2016-10-17 11:08:57 +0900 [info]: starting fluentd-0.12.26
2016-10-17 11:08:57 +0900 [info]: gem 'fluent-mixin-config-placeholders' version '0.4.0'
2016-10-17 11:08:57 +0900 [info]: gem 'fluent-mixin-plaintextformatter' version '0.2.6'
2016-10-17 11:08:57 +0900 [info]: gem 'fluent-plugin-kinesis' version '1.1.0'
2016-10-17 11:08:57 +0900 [info]: gem 'fluent-plugin-mongo' version '0.7.13'
2016-10-17 11:08:57 +0900 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '1.5.5'
2016-10-17 11:08:57 +0900 [info]: gem 'fluent-plugin-s3' version '0.6.8'
2016-10-17 11:08:57 +0900 [info]: gem 'fluent-plugin-scribe' version '0.10.14'
2016-10-17 11:08:57 +0900 [info]: gem 'fluent-plugin-td' version '0.10.28'
2016-10-17 11:08:57 +0900 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.2'
2016-10-17 11:08:57 +0900 [info]: gem 'fluent-plugin-webhdfs' version '0.4.2'
2016-10-17 11:08:57 +0900 [info]: gem 'fluentd' version '0.12.26'
2016-10-17 11:08:57 +0900 [info]: adding filter pattern="log" type="record_transformer"
2016-10-17 11:08:57 +0900 [info]: adding match pattern="log" type="kinesis_producer"
2016-10-17 11:08:57 +0900 [info]: adding source type="tail"
2016-10-17 11:08:57 +0900 [info]: adding source type="monitor_agent"
2016-10-17 11:08:57 +0900 [info]: using configuration file: 
<ROOT>
  <source>
    @type tail
    format ltsv
    path /var/log/some/*.log
    pos_file /var/log/td-agent/log.pos
    read_from_head true
    tag log
    keys time
  </source>
  <filter log>
    type record_transformer
    <record>
      hostname ${hostname}
    </record>
  </filter>
  <match log>
    @type kinesis_producer
    stream_name stream
    region ap-northeast-1
    aws_key_id xxxxxx
    aws_sec_key xxxxxx
    buffer_type file
    buffer_path /var/log/td-agent/buffer/log
    flush_at_shutdown true
    <kinesis_producer>
      record_ttl 300000
    </kinesis_producer>
  </match>
  <source>
    type monitor_agent
    bind 127.0.0.1
    port 24220
  </source>
</ROOT>
```

**Comment by riywo** [comment]
Hi,

Could you provide more information of the failure, e.g. output messages?

Best,

**Comment by llby** [comment]
I find other warning.

```
  2016-10-17 18:17:42 +0900 [warn]: emit transaction failed: error_class=Fluent::BufferQueueLimitError error="queue size exceeds limit" tag="log"
  2016-10-17 18:17:42 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/buffer.rb:204:in `block in emit'
  2016-10-17 18:17:42 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
  2016-10-17 18:17:42 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/buffer.rb:193:in `emit'
  2016-10-17 18:17:42 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:268:in `emit'
  2016-10-17 18:17:42 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/event_router.rb:154:in `emit'
  2016-10-17 18:17:42 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/event_router.rb:90:in `emit_stream'
  2016-10-17 18:17:42 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/plugin/in_tail.rb:269:in `receive_lines'
  2016-10-17 18:17:42 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/plugin/in_tail.rb:373:in `call'
  2016-10-17 18:17:42 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/plugin/in_tail.rb:373:in `wrap_receive_lines'
  2016-10-17 18:17:42 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/plugin/in_tail.rb:568:in `call'
  2016-10-17 18:17:42 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/plugin/in_tail.rb:568:in `on_notify'
  2016-10-17 18:17:42 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/plugin/in_tail.rb:399:in `on_notify'
  2016-10-17 18:17:42 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/plugin/in_tail.rb:500:in `call'
  2016-10-17 18:17:42 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/plugin/in_tail.rb:500:in `on_change'
  2016-10-17 18:17:42 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.4/lib/cool.io/loop.rb:88:in `run_once'
  2016-10-17 18:17:42 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.4/lib/cool.io/loop.rb:88:in `run'
  2016-10-17 18:17:42 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/plugin/in_tail.rb:253:in `run'

```

**Comment by riywo** [comment]
Thanks. Do you have any metric info related to this event? I can see you use monitor_agent so that you would record metrics. Also, KPL sends metrics to Amazon CloudWatch which is useful if you can provide it.

**Comment by llby** [comment]
ok.

- 2016/10/14 11:00
    - AWS/Kinesis WriteProvisionedThroughputExceeded -> Instantaneously many
    - KinesisProducerLibrary RetriesPerRecord ->  Instantaneously many
    - KinesisProducerLibrary UserRecordExpired -> Instantaneously many（all shard）
    - KinesisProducerLibrary RequestTime -> Instantaneously many
    - KinesisProducerLibrary ErrorsByCode InternalFailure -> Instantaneously many
    - KinesisProducerLibrary ErrorsByCode Http500 -> Instantaneously many
- 2016/10/15 10:00
    - AWS/EC2 CPUUtilization -> about 2 times

**Comment by riywo** [comment]
Hi @llby ,

Sorry for super delay. Are you still seeing this issue? It seems that your kinesis capacity was full because WriteProvisionedThroughputExceeded metric increased.

**Comment by llby** [comment]
Maybe. I think so, too.
You means
When kinesis catpacity was full, plugin kinesis_produce freeze?

**Comment by riywo** [comment]
I'm sorry for no response for a long time. We're are going to release [v2.0.0](https://github.com/awslabs/aws-fluent-plugin-kinesis/pull/112) which supports record aggregation by a different way without KPL. So, this problem never happen and I'm closing.

Please try v2.0.0 first. If you need more help, feel free to add comment.
